version: "3"

services:
  web:
    container_name: web-client-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 80:4000
#       ^    ^
#  External Internal

  proxy-server:
    working_dir: /app
    container_name: proxy-server
    image: express-gateway:latest
    volumes:
      - './proxy_server:/app' # Copy all contents of ./proxy-server over to container
    entrypoint: ['node', 'server.js']
    ports: 
        - 3030:3030