version: "3"

services:
  web:
    container_name: dev-client
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true

  proxy-server:
    working_dir: /app
    container_name: proxy-server
    image: express-gateway:latest
    volumes:
      - './proxy_server:/app' # Copy all contents of ./proxy-server to container
    entrypoint: ['node', 'server.js']
    ports: 
        - 3030:3030